# Generated by Django 3.0.4 on 2020-04-10 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('1', 'Produkty spożywcze'), ('2', 'Chemia gospodarcza'), ('3', 'Ubrania'), ('4', 'Rozrywka'), ('5', 'Alkohol'), ('6', 'Rozwój osobisty'), ('7', 'Suplementy'), ('8', 'Inne')], max_length=1)),
                ('purchase_date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
