# Generated by Django 3.0.4 on 2020-03-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('1', 'Produkty spożywcze'), ('2', 'Chemia gospodarcza'), ('3', 'Ubrania'), ('4', 'Rozrywka'), ('5', 'Alkohol'), ('6', 'Rozwój osobisty'), ('7', 'Suplementy'), ('8', 'Inne')], max_length=1)),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
